= Autocrafting Monitor
:icon: autocrafting-monitor.png
:from: v0.6.0-alpha

The {doctitle} displays the status of all active autocrafting tasks.

Each task is shown as a grid of cells, where each cell represents how a resource is used in the task.

Terminology used in cells:

- **Stored** – The resource is held in the task's internal inventory, to be used later.
- **Processing** – The resource is currently inserted into an external machine.
- **Scheduled** – The resource is queued for crafting and will be processed later.
- **Crafting** – The resource itself is being crafted.

The {doctitle} also shows if a resource was not accepted by an external machine or if a xref:autocrafter.adoc[] is currently locked.

== Cancelling tasks

Tasks can be cancelled individually or all at once.

If there is not enough space in the storage network to cancel the autocrafting task, the task will not be cancelled, or will be partially cancelled.

include::../../partials/connections-all.adoc[]

include::../../partials/redstone-mode.adoc[]

include::../../partials/recoloring.adoc[]
