= Storing externally

So far, you've used xref:index.adoc#_storage_disks[storage disks] or xref:index.adoc#_storage_blocks[storage blocks] for storage.
But what if you want to use a chest or another external inventory as storage in the storage network?

== The External Storage

Craft an xref:../storage/external-storage.adoc[] and connect it to an external inventory, such as a link:https://minecraft.gamepedia.com/Chest[Chest].

Once connected, resources inserted into the storage network will be stored in the external inventory.

You can also use filter slots to control which resources can enter the external inventory.

== Supported Storages

The xref:../storage/external-storage.adoc[] works with any block that functions as an inventory. Examples include:

- link:https://minecraft.gamepedia.com/Chest[Chests]
- Storage Drawers
- Regular Drawers
- Drawer Controllers
- Iron Chests
- And more...

== Prioritizing External Storage

When inserting or extracting resources, the storage network prioritizes storage with the **highest priority** first.

To control where resources go:

1. Assign a **higher priority** to the preferred storage.
2. If the preferred storage is full, the network will attempt to use the next available storage with a lower priority.

You may differentiate between the insert and extract priorities.
