= Wireless Transmitter
:icon: wireless-transmitter.png
:from: v0.6.0-alpha

To use wireless tools, the storage network must be accessible wirelessly by installing {doctitle}s in the network.

== Range

The default range is 16 blocks but can be extended with xref:../upgrades/range-upgrade.adoc[range upgrades].

== Multiple {doctitle}s in a network

A storage network can have multiple {doctitle}s. Distribute them strategically, each upgraded with xref:../upgrades/range-upgrade.adoc[range upgrades], to maximize coverage.

== Efficient placement

Placing two {doctitle}s next to each other has minimal effect on range.

Since the wireless signal originates from the {doctitle}'s position, adjacent transmitters provide only a **1-block net gain**. To optimize range, spread transmitters across the network.

== Applicable upgrades

- xref:../upgrades/range-upgrade.adoc[] (4)
* Increases the base range of the {doctitle}.
- xref:../upgrades/creative-range-upgrade.adoc[] (1)
* Grants infinite range to the {doctitle}.

include::../../partials/redstone-mode.adoc[]

include::../../partials/recoloring.adoc[]
