name: Build
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    uses: refinedmods/refinedarchitect/.github/workflows/build.yml@v1.2.0
    with:
      version: v2.0.0-beta.1
      gametests: true
    secrets: inherit
