name: Build
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set version number
        if: ${{ inputs.version != '' }}
        run: |
          echo "RELEASE_VERSION=v2.0.0-beta.1" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Java
        uses: refinedmods/refinedarchitect/.github/actions/setup-java@develop
      # https://docs.sonarqube.org/latest/analysis/github-integration/
      - name: Build and test
        run: ./gradlew build codeCoverageReportAggregate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Gametests
        if: ${{ inputs.gametests == true }}
        run: ./gradlew runGameTestServer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: '**/build/libs/'